### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by davidpham87** [oliyh/re-jump.el#10]
Hello,

I think the packages only work for keywords events, would it be possible to extend it to subscriptions as well?

Cheers,
David

**Comment by oliyh** [comment]
Hi,

It works for subs too - it's looking for `reg-* ::kw`

Is it working for events but not subs for you?

Cheers

**Comment by davidpham87** [comment]
Hello, 

Indeed, it is working for events but not subscriptions.  The error message is  `Can't find namespace xyz.subs`. It expands correctly the fully qualified keyword but then does not find the associated namespace. I find it extremely odd, sorry. Maybe it is an issue about Cider? I use 0.22.3

**Comment by oliyh** [comment]
Hi,

That error happens earlier in the flow trying to discover which namespace to look for the handler in. Are your events in a different namespace to your subs?

It works for me on Cider 21.1 at least. If it broke because of Cider I'd expect it to not work for anything, I think there must be a difference in the way your subs namespace is declared. I'm guessing it must have been `require`d in, so the REPL is aware of it?

Is there a minimal failing chunk of code you can reproduce this with?

Cheers

**Comment by davidpham87** [comment]
Yes, my subscriptions are in a different namespace as my events. When I place my subscription in the same namespace, `re-jump` finds the keyword.

I will work on an example with minimal code for reproducing it. 

I find it odd, that the `cider-find-ns` fails to open me a few namespaces. I use a standard re-frame folder architecture (with individual panels having their own namespace) and with the 5/6 files per panels. I can't why cider-find-ns succeed or not. The function that is failing is `cider-sync-request:ns-path`

Thanks for your help! At least I know where to dig in :-) Sorry for disturbing.

**Comment by davidpham87** [comment]
Cider related.
